/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import Services.ServicePays;
import Services.verif;
import classs.Pays;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.text.MessageFormat;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class FrmPaysAdm extends javax.swing.JInternalFrame {

    private static ArrayList<Pays> lstPays;
    private JTable table;
    private int id = 0;
    private String nom = "";
    private String date = "";
    /**
     * Creates new form FrmPaysAdm
     */
    private static DefaultTableModel model = new DefaultTableModel(new Object[][]{}, new String[]{"ID_P", "Nom_P", "DateU", "T_Cas", "T_Décés", "T_Tests", "T_Recupere"});

    public void JTablePeuplerTous() {
        ServicePays gest = new ServicePays();

        lstPays = gest.findAll();
        String[] data = new String[7];
        for (Pays p : lstPays) {
            data[0] = p.getIdP() + "";
            data[1] = p.getNomP() + "";
            data[2] = p.getDateU() + "";
            data[3] = p.getTcas() + "";
            data[4] = p.getTdeces() + "";
            data[5] = p.getTtest() + "";
            data[6] = p.getTrecup() + "";

            model.addRow(data);
        }

    }

    public void clear() {
        nvcas.setText("");
        nvcri.setText("");
        nvdeces.setText("");
        nvre.setText("");
        nvtests.setText("");
        Tcas.setText("");
        Tdeces.setText("");
        Ttst.setText("");
        Tre.setText("");
        dateU.setText("");

    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {

        // get the selected row index
        int selectedRowIndex = table.getSelectedRow();

        //ncinTxt.setText(lstPays.get(selectedRowIndex).getIdP());
        cbP.setSelectedItem(lstPays.get(selectedRowIndex).getNomP());
        Tcas.setText(lstPays.get(selectedRowIndex).getTcas() + "");
        Tdeces.setText(lstPays.get(selectedRowIndex).getTdeces() + "");
        Ttst.setText(lstPays.get(selectedRowIndex).getTtest() + "");
        Tre.setText(lstPays.get(selectedRowIndex).getTrecup() + "");
        nvcas.setText(lstPays.get(selectedRowIndex).getNvcas() + "");
        nvdeces.setText(lstPays.get(selectedRowIndex).getNvdeces() + "");
        nvtests.setText(lstPays.get(selectedRowIndex).getNvtest() + "");
        nvre.setText(lstPays.get(selectedRowIndex).getNvrecup() + "");
        nvcri.setText(lstPays.get(selectedRowIndex).getNvcritique() + "");
        dateU.setEnabled(false);
        cbP.setEnabled(false);
        con.setEnabled(false);
    }

    public FrmPaysAdm() {
        super("PAYS-ADMIN",
                true, //resizable
                true, //closable
                true, //maximizable
                true); //iconifiable
        super.setTitle("Pays");
        this.setSize(900, 580);
        initComponents();
        JScrollPane scrollPane = new JScrollPane();
        //scrollPane.setBackground(Color.red);
        getContentPane().add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 580, 300));
        table = new JTable();

        table.setEnabled(true);
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table.setModel(model);
        scrollPane.setViewportView(table);
        JTableHeader header = table.getTableHeader();
        header.setFont(new Font("calibri", Font.BOLD, 18));
        header.setForeground(new Color(0, 0, 0));

        table.setPreferredScrollableViewportSize(new Dimension(250, 62));

        table.setFont(new Font("calibri", Font.BOLD, 16));
        table.setRowHeight(20);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });

        for (int i = model.getRowCount(); i > 0; --i) {
            model.removeRow(i - 1);
        }
        JTablePeuplerTous();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbP = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        background = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Tcas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Tdeces = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Ttst = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Tre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nvcas = new javax.swing.JTextField();
        nvdeces = new javax.swing.JTextField();
        nvtests = new javax.swing.JTextField();
        nvre = new javax.swing.JTextField();
        nvcri = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        dateU = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        con = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pays", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 2, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("Pays");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        cbP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afghanistan", "Afrique du Sud", "Albanie", "Algérie", "Allemagne", "Andorre", "Angola", "Antigua-et-Barbuda", "Arabie saoudite", "Argentine", "Arménie", "Australie", "Autriche", "Azerbaïdjan", "Bahamas", "Bahreïn", "Bangladesh", "Barbade", "Belgique", "Belize", "Bénin", "Bhoutan", "Biélorussie", "Birmanie", "Bolivie", "Bosnie-Herzégovine", "Botswana", "Brésil", "Brunei", "Bulgarie", "Burkina Faso", "Burundi", "Cambodge", "Cameroun", "Canada", "Cap-Vert", "Chili", "Chine", "Chypre", "Colombie", "Comores", "îles Cook", "Corée du Nord", "Corée du Sud", "Costa Rica", "Côte d'Ivoire", "Cuba", "Danemark", "Djibouti", "Dominique", "Égypte", "Équateur", "Érythrée", "Espagne", "Estonie", "États-Unis", "Éthiopie", "Fidji", "Finlande", "France", "Gabon", "Gambie", "Géorgie", "Ghana", "Grèce", "Grenade", "Guatemala", "Guinée", "Guinée-Bissau", "Guyana", "Haïti", "Honduras", "Hongrie", "Inde", "Indonésie", "Irak", "Iran", "Irlande", "Islande", "Israël", "Italie", "Jamaïque", "Japon", "Jordanie", "Kazakhstan", "Kenya", "Kirghizistan", "Kiribati", "Koweït", "Laos", "Lesotho", "Lettonie", "Liban", "Liberia", "Libye", "Liechtenstein", "Lituanie", "Luxembourg", "Macédoine du Nord", "Madagascar", "Malaisie", "Malawi", "Maldives", "Mali", "Malte", "Maroc", "Îles Marshall", "Maurice", "Mauritanie", "Mexique", "Micronésie", "Moldavie", "Monaco", "Mongolie", "Monténégro", "Mozambique", "Namibie", "Nauru", "Népal", "Nicaragua", "Niger", "Nigeria", "Niue", "Norvège", "Nouvelle-Zélande", "Oman", "Ouganda", "Ouzbékistan", "Pakistan", "Palaos", "Palestine Palestine", "Panamá", "Paraguay", "Pays-Bas", "Pérou", "Philippines", "Pologne", "Portugal", "Qatar", "Roumanie", "Russie", "Rwanda", "Sainte-Lucie", "Îles Salomon", "Salvador", "Samoa", "Sénégal", "Serbie", "Seychelles", "Sierra Leone", "Singapour", "Slovaquie", "Slovénie", "Somalie", "Soudan", "Soudan du Sud", "Sri Lanka", "Suède", "Suisse", "Suriname", "Eswatini", "Syrie", "Tadjikistan", "Tanzanie", "Tchad", "Thaïlande", "Timor oriental", "Togo", "Tonga", "Tunisie", "Turkménistan", "Turquie", "Tuvalu", "Ukraine", "Uruguay", "Vanuatu", "Vatican", "Venezuela", "Viêt Nam", "Yémen", "Zambie", "Zimbabwe" }));
        jPanel3.add(cbP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 210, 70));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Totale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 2, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setName("background"); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 28, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setText("Total cas ");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel1.add(Tcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 370, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setText("total décés ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        Tdeces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TdecesActionPerformed(evt);
            }
        });
        jPanel1.add(Tdeces, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 370, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("Total tests");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel1.add(Ttst, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 370, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_calculator_16px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 40, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setText("total recuperer");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel1.add(Tre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 370, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 590, 200));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nouvelles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 2, 14))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 204, 204));
        jPanel2.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setText("NVT-cas");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setText("NVT-décés");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setText("NVT-tests");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setText("NVT-recupérer");
        jLabel10.setToolTipText("");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel11.setText("NVT-critiqué");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel2.add(nvcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 100, -1));
        jPanel2.add(nvdeces, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 100, -1));
        jPanel2.add(nvtests, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 100, -1));
        jPanel2.add(nvre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 100, -1));
        jPanel2.add(nvcri, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, 190));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_add_30px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 70, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_flip_chart_50px_1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 80, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_unavailable_24px.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 80, 50));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date Update", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(dateU, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, 80));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setText("continent");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        con.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afrique", "Amerique", "Asie", "Océanie", "Europe", "Antarctique" }));
        getContentPane().add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 110, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_print_64px.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 80, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        ServicePays P1 = new ServicePays();
        Pays gg = new Pays();
        gg = P1.findAllDay(cbP.getSelectedItem() + "");
        Tcas.setText((gg.getTcas() + Integer.parseInt(nvcas.getText())) + "");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        ServicePays P1 = new ServicePays();
        Pays gg = new Pays();
        gg = P1.findAllDay(cbP.getSelectedItem() + "");
        Tdeces.setText((gg.getTdeces() + Integer.parseInt(nvdeces.getText())) + "");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void TdecesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TdecesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TdecesActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ServicePays P1 = new ServicePays();
        Pays gg = new Pays();
        gg = P1.findAllDay(cbP.getSelectedItem() + "");
        Ttst.setText((gg.getTtest() + Integer.parseInt(nvtests.getText())) + "");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ServicePays P1 = new ServicePays();
        Pays gg = new Pays();
        gg = P1.findAllDay(cbP.getSelectedItem() + "");
        Tre.setText((gg.getTrecup() + Integer.parseInt(nvre.getText())) + "");
        Ttst.setText((gg.getTtest() + Integer.parseInt(nvtests.getText())) + "");
        Tdeces.setText((gg.getTdeces() + Integer.parseInt(nvdeces.getText())) + "");
        Tcas.setText((gg.getTcas() + Integer.parseInt(nvcas.getText())) + "");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        ServicePays P1 = new ServicePays();
        Pays gg = new Pays();
        gg = P1.findAllDay(cbP.getSelectedItem() + "");
        Tre.setText((gg.getTrecup() + Integer.parseInt(nvre.getText())) + "");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        
        int j = 0;
        verif ver = new verif();
        if (nvcas.getText() == "" || nvdeces.getText() == "" || nvcri.getText() == "" || nvre.getText() == "" || nvtests.getText() == "") {
            JOptionPane.showMessageDialog(null, "chaine vide non accepté");
            j = 1;
        }
        if (ver.verifDate(dateU.getText())!=true) {
            JOptionPane.showMessageDialog(null, "date incorrect");
            j = 1;
        }
        if (ver.verifDigit(Tcas.getText()) != true) {
            JOptionPane.showMessageDialog(null, "Total cas incorrect");
            j = 1;
        }
        if (ver.verifDigit(Tdeces.getText()) != true) {
            JOptionPane.showMessageDialog(null, "Total deces incorrect");
            j = 1;
        }
        if (ver.verifDigit(Tre.getText()) != true) {
            JOptionPane.showMessageDialog(null, "Total recuperé incorrect");
            j = 1;
        }
        if (ver.verifDigit(Ttst.getText()) != true) {
            JOptionPane.showMessageDialog(null, "Total tests incorrect");
            j = 1;
        }
        if (ver.verifDigit(nvcas.getText()) != true) {
            JOptionPane.showMessageDialog(null, "nombre de nouvelles cas incorrect");
            j = 1;
        }
        if (ver.verifDigit(nvdeces.getText()) != true) {
            JOptionPane.showMessageDialog(null, "nombre de nouvelles deces incorrect");
            j = 1;
        }
        if (ver.verifDigit(nvre.getText()) != true) {
            JOptionPane.showMessageDialog(null, "nombre de nouvelles recuperé incorrect");
            j = 1;
        }
        if (ver.verifDigit(nvtests.getText()) != true) {
            JOptionPane.showMessageDialog(null, "nombre de nouvelles tests incorrect");
            j = 1;
        }
        if (ver.verifDigit(nvcri.getText()) != true) {
            JOptionPane.showMessageDialog(null, "nombre de nouvelles cas critiques incorrect");
            j = 1;
        }
        if (j == 0) {
            Pays p = new Pays(
                    (String) cbP.getSelectedItem(),
                    20,
                    dateU.getText(),
                    Integer.parseInt(Tcas.getText()),
                    Integer.parseInt(nvcas.getText()),
                    Integer.parseInt(Tdeces.getText()),
                    Integer.parseInt(nvdeces.getText()),
                    Integer.parseInt(Tre.getText()),
                    Integer.parseInt(nvre.getText()),
                    Integer.parseInt(Ttst.getText()),
                    Integer.parseInt(nvtests.getText()),
                    Integer.parseInt(nvcri.getText()),
                    (String) con.getSelectedItem()
            );

            ServicePays P1 = new ServicePays();
            boolean v;
            try {
                v = P1.create(p);

                if (v == true) {
                    String[] data = new String[7];
                    data[0] = p.getIdP() + "";
                    data[1] = p.getNomP() + "";
                    data[2] = p.getDateU() + "";
                    data[3] = p.getTcas() + "";
                    data[4] = p.getTdeces() + "";
                    data[5] = p.getTtest() + "";
                    data[6] = p.getTrecup() + "";

                    model.addRow(data);

                    //JOptionPane.showMessageDialog(null,gg.toString() );
                } else {
                    clear();
                }
            } catch (ParseException ex) {
                Logger.getLogger(FrmPaysAdm.class.getName()).log(Level.SEVERE, null, ex);
                clear();
            }

            for (int i = model.getRowCount(); i > 0; --i) {
                model.removeRow(i - 1);
            }
            JTablePeuplerTous();
        }
        else {
            System.out.println("erreur !!! ");
        }
        clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int j = 0;
        verif ver = new verif();
        if (nvcas.getText() == "" || nvdeces.getText() == "" || nvcri.getText() == "" || nvre.getText() == "" || nvtests.getText() == "") {
            JOptionPane.showMessageDialog(null, "chaine vide non accepté");
            j = 1;
        }
       
        if (ver.verifDigit(Tcas.getText()) != true) {
            JOptionPane.showMessageDialog(null, "Total cas incorrect");
            j = 1;
        }
        if (ver.verifDigit(Tdeces.getText()) != true) {
            JOptionPane.showMessageDialog(null, "Total deces incorrect");
            j = 1;
        }
        if (ver.verifDigit(Tre.getText()) != true) {
            JOptionPane.showMessageDialog(null, "Total recuperé incorrect");
            j = 1;
        }
        if (ver.verifDigit(Ttst.getText()) != true) {
            JOptionPane.showMessageDialog(null, "Total tests incorrect");
            j = 1;
        }
        if (ver.verifDigit(nvcas.getText()) != true) {
            JOptionPane.showMessageDialog(null, "nombre de nouvelles cas incorrect");
            j = 1;
        }
        if (ver.verifDigit(nvdeces.getText()) != true) {
            JOptionPane.showMessageDialog(null, "nombre de nouvelles deces incorrect");
            j = 1;
        }
        if (ver.verifDigit(nvre.getText()) != true) {
            JOptionPane.showMessageDialog(null, "nombre de nouvelles recuperé incorrect");
            j = 1;
        }
        if (ver.verifDigit(nvtests.getText()) != true) {
            JOptionPane.showMessageDialog(null, "nombre de nouvelles tests incorrect");
            j = 1;
        }
        if (ver.verifDigit(nvcri.getText()) != true) {
            JOptionPane.showMessageDialog(null, "nombre de nouvelles cas critiques incorrect");
            j = 1;
        }
        if (j == 0) {
            ServicePays P1 = new ServicePays();
            int selectedRowIndex = table.getSelectedRow();
            id = lstPays.get(selectedRowIndex).getIdP();
            nom = lstPays.get(selectedRowIndex).getNomP();
            date = lstPays.get(selectedRowIndex).getDateU();

            Pays p = new Pays(
                    nom,
                    id,
                    date,
                    Integer.parseInt(Tcas.getText()),
                    Integer.parseInt(nvcas.getText()),
                    Integer.parseInt(Tdeces.getText()),
                    Integer.parseInt(nvdeces.getText()),
                    Integer.parseInt(Tre.getText()),
                    Integer.parseInt(nvre.getText()),
                    Integer.parseInt(Ttst.getText()),
                    Integer.parseInt(nvtests.getText()),
                    Integer.parseInt(nvcri.getText()),
                    (String) con.getSelectedItem());

            P1.updateP(p);
            if (P1.updateP(p) != true) {

                clear();
            }

            //model.setRowCount(0);
            for (int i = model.getRowCount(); i > 0; --i) {
                model.removeRow(i - 1);
            }
            JTablePeuplerTous();
             dateU.setEnabled(true);
        cbP.setEnabled(true);
        con.setEnabled(true);
        }
        clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ServicePays P1 = new ServicePays();
        int selectedRowIndex = table.getSelectedRow();
        id = lstPays.get(selectedRowIndex).getIdP();
        nom = lstPays.get(selectedRowIndex).getNomP();
        date = lstPays.get(selectedRowIndex).getDateU();

        boolean v = P1.delete(id, nom, date);
        
        if (v == true) {
          
            for (int i = model.getRowCount(); i > 0; --i) {
                model.removeRow(i - 1);
            }
            JTablePeuplerTous();
        } else {
            clear();
        }
        clear();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Governorat");
        MessageFormat footer = new MessageFormat("page{0,number,Integer}");
        try {
            table.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.println("erooor" + e.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tcas;
    private javax.swing.JTextField Tdeces;
    private javax.swing.JTextField Tre;
    private javax.swing.JTextField Ttst;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox cbP;
    private javax.swing.JComboBox con;
    private javax.swing.JTextField dateU;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField nvcas;
    private javax.swing.JTextField nvcri;
    private javax.swing.JTextField nvdeces;
    private javax.swing.JTextField nvre;
    private javax.swing.JTextField nvtests;
    // End of variables declaration//GEN-END:variables
}
