--------------------------------------------------------
--  Fichier créé - samedi-juin-13-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DEMANDE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJET"."DEMANDE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 ORDER  CYCLE ;
--------------------------------------------------------
--  DDL for Sequence GOUVERNORAT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJET"."GOUVERNORAT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HOPITALE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJET"."HOPITALE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PAYS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJET"."PAYS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJET"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DEMANDE
--------------------------------------------------------

  CREATE TABLE "PROJET"."DEMANDE" 
   (	"ID" NUMBER(*,0), 
	"ID_HOSPITAL" NUMBER(*,0), 
	"TYPE" VARCHAR2(60 BYTE), 
	"TITRE" VARCHAR2(100 BYTE), 
	"DISTINATAIRE" VARCHAR2(60 BYTE), 
	"TEXT_D" VARCHAR2(400 BYTE), 
	"PRIX_ESTIME" FLOAT(126), 
	"RESPONSABLE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GOUVERNORAT
--------------------------------------------------------

  CREATE TABLE "PROJET"."GOUVERNORAT" 
   (	"NOMGV" VARCHAR2(70 BYTE), 
	"ID_G" NUMBER(*,0), 
	"DATE_UPDATE" DATE, 
	"TOTAL_CAS" NUMBER(*,0), 
	"NVL_CAS" NUMBER(*,0), 
	"TOTAL_DECES" NUMBER(*,0), 
	"NVL_DECES" NUMBER(*,0), 
	"TOTAL_RECUPERE" NUMBER(*,0), 
	"NVL_RECUPERE" NUMBER(*,0), 
	"TOTAL_TEST" NUMBER(*,0), 
	"NVL_TEST" NUMBER(*,0), 
	"NVL_CRITIQUE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HOPITALE
--------------------------------------------------------

  CREATE TABLE "PROJET"."HOPITALE" 
   (	"ID" NUMBER(*,0), 
	"NOM" VARCHAR2(50 BYTE), 
	"ADRESSE" VARCHAR2(100 BYTE), 
	"GOV" VARCHAR2(50 BYTE), 
	"NBR_CAS_HOSPITALISE" NUMBER(*,0), 
	"LITS_DISPO_REA" NUMBER(*,0), 
	"DATE_UPDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAYS
--------------------------------------------------------

  CREATE TABLE "PROJET"."PAYS" 
   (	"NOMPAYS" VARCHAR2(50 BYTE), 
	"ID_PAYS" NUMBER(*,0), 
	"DATE_UPDATE" DATE, 
	"TOTAL_CAS" NUMBER(*,0), 
	"NVL_CAS" NUMBER(*,0) DEFAULT 0, 
	"TOTAL_DECES" NUMBER(*,0), 
	"NVL_DECES" NUMBER(*,0) DEFAULT 0, 
	"TOTAL_RECUPERE" NUMBER(*,0), 
	"NVL_RECUPERE" NUMBER(*,0) DEFAULT 0, 
	"TOTAL_TEST" NUMBER(*,0), 
	"NVL_TEST" NUMBER(*,0) DEFAULT 0, 
	"NVL_CRITIQUE" NUMBER(*,0) DEFAULT 0, 
	"CONTINENT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNE
--------------------------------------------------------

  CREATE TABLE "PROJET"."PERSONNE" 
   (	"CIN" VARCHAR2(8 BYTE), 
	"GOV" VARCHAR2(50 BYTE), 
	"DATE_UPDATE" DATE, 
	"SEXE" CHAR(1 BYTE), 
	"AGE" NUMBER(*,0), 
	"CAS_IMPORTES" NUMBER(*,0), 
	"ID_GOV" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "PROJET"."USERS" 
   (	"ID" NUMBER(*,0), 
	"ADMIN" NUMBER(*,0), 
	"LOGIN" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PROJET.DEMANDE
SET DEFINE OFF;
REM INSERTING into PROJET.GOUVERNORAT
SET DEFINE OFF;
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Kef','3',to_date('01/01/20','DD/MM/RR'),'1','1','1','1','1','1','1','1','1');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Jendouba','4',to_date('12/10/20','DD/MM/RR'),'2','2','2','2','2','2','2','2','2');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Bizerte','5',to_date('20/10/20','DD/MM/RR'),'1117','2','7','2','27','2','7','2','2');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Jendouba','6',to_date('01/01/20','DD/MM/RR'),'6','4','7','5','7','5','7','5','5');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Kairouan','7',to_date('13/03/20','DD/MM/RR'),'1','1','4','4','4','4','4','4','4');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Kasserine','8',to_date('01/01/20','DD/MM/RR'),'2','2','2','2','65','65','5','5','5');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Bizerte','11',to_date('20/12/20','DD/MM/RR'),'1120','3','10','3','30','3','10','3','3');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Sfax','12',to_date('01/01/20','DD/MM/RR'),'2','2','5','5','5','5','5','5','5');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Sousse','13',to_date('01/01/20','DD/MM/RR'),'2','2','2','2','2','2','2','2','2');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Bizerte','14',to_date('01/01/20','DD/MM/RR'),'1','1','1','1','1','1','1','1','1');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Bizerte','15',to_date('01/01/20','DD/MM/RR'),'1375','255','64','54','84','54','14','4','54');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Bizerte','16',to_date('13/06/17','DD/MM/RR'),'1122','2','12','2','32','2','12','2','2');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Béja','17',to_date('13/03/20','DD/MM/RR'),'2','2','5','5','9','9','8','8','8');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Kairouan','18',to_date('12/03/20','DD/MM/RR'),'3','2','9','5','55','51','9','5','56');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Kairouan','19',to_date('12/03/20','DD/MM/RR'),'3','2','9','5','55','51','9','5','56');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Sidi Bouzid','20',to_date('13/12/20','DD/MM/RR'),'2','2','8','8','8','8','8','8','8');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Siliana','21',to_date('15/03/20','DD/MM/RR'),'2','2','7','7','4','4','47','47','47');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Sidi Bouzid','22',to_date('15/03/20','DD/MM/RR'),'4','2','13','5','549','541','62','54','5');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Kasserine','41',to_date('18/03/20','DD/MM/RR'),'1122','2','12','2','88','58','15','5','58');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Bizerte','42',to_date('17/03/20','DD/MM/RR'),'1122','2','66','56','619','589','66','56','589');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Bizerte','1',to_date('01/01/20','DD/MM/RR'),'1115','1115','5','5','25','25','5','5','6');
Insert into PROJET.GOUVERNORAT (NOMGV,ID_G,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE) values ('Bizerte','2',to_date('01/01/20','DD/MM/RR'),'1116','1','7','2','30','5','10','5','5');
REM INSERTING into PROJET.HOPITALE
SET DEFINE OFF;
Insert into PROJET.HOPITALE (ID,NOM,ADRESSE,GOV,NBR_CAS_HOSPITALISE,LITS_DISPO_REA,DATE_UPDATE) values ('1','fgh','drtfyghj','Bizerte','6','5',to_date('08/03/20','DD/MM/RR'));
REM INSERTING into PROJET.PAYS
SET DEFINE OFF;
Insert into PROJET.PAYS (NOMPAYS,ID_PAYS,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE,CONTINENT) values ('Item 3','21',to_date('12/10/20','DD/MM/RR'),'500','20','124','10','554','12','224','21','30','Asie');
Insert into PROJET.PAYS (NOMPAYS,ID_PAYS,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE,CONTINENT) values ('Item 3','22',to_date('12/03/20','DD/MM/RR'),'500','21','100','10','554','12','224','21','30','Afrique');
Insert into PROJET.PAYS (NOMPAYS,ID_PAYS,DATE_UPDATE,TOTAL_CAS,NVL_CAS,TOTAL_DECES,NVL_DECES,TOTAL_RECUPERE,NVL_RECUPERE,TOTAL_TEST,NVL_TEST,NVL_CRITIQUE,CONTINENT) values ('Item 4','24',to_date('12/10/10','DD/MM/RR'),'15','10','10','10','10','10','10','10','10','Afrique');
REM INSERTING into PROJET.PERSONNE
SET DEFINE OFF;
Insert into PROJET.PERSONNE (CIN,GOV,DATE_UPDATE,SEXE,AGE,CAS_IMPORTES,ID_GOV) values ('22222222','Kairouan',to_date('13/03/20','DD/MM/RR'),'F','18','0','7');
Insert into PROJET.PERSONNE (CIN,GOV,DATE_UPDATE,SEXE,AGE,CAS_IMPORTES,ID_GOV) values ('88888888','Kasserine',to_date('01/01/20','DD/MM/RR'),'F','18','1','8');
Insert into PROJET.PERSONNE (CIN,GOV,DATE_UPDATE,SEXE,AGE,CAS_IMPORTES,ID_GOV) values ('22822922','Kairouan',to_date('13/03/20','DD/MM/RR'),'F','18','0','7');
Insert into PROJET.PERSONNE (CIN,GOV,DATE_UPDATE,SEXE,AGE,CAS_IMPORTES,ID_GOV) values ('99999999','Kairouan',to_date('13/03/20','DD/MM/RR'),'F','18','0','7');
Insert into PROJET.PERSONNE (CIN,GOV,DATE_UPDATE,SEXE,AGE,CAS_IMPORTES,ID_GOV) values ('77777777','Kairouan',to_date('13/03/20','DD/MM/RR'),'F','18','0','7');
Insert into PROJET.PERSONNE (CIN,GOV,DATE_UPDATE,SEXE,AGE,CAS_IMPORTES,ID_GOV) values ('62626262','Bizerte',to_date('20/12/20','DD/MM/RR'),'F','52','1','11');
Insert into PROJET.PERSONNE (CIN,GOV,DATE_UPDATE,SEXE,AGE,CAS_IMPORTES,ID_GOV) values ('87878787','Bizerte',to_date('20/12/20','DD/MM/RR'),'F','10','0','11');
Insert into PROJET.PERSONNE (CIN,GOV,DATE_UPDATE,SEXE,AGE,CAS_IMPORTES,ID_GOV) values ('55555555','Bizerte',to_date('20/12/20','DD/MM/RR'),'F','33','0','11');
Insert into PROJET.PERSONNE (CIN,GOV,DATE_UPDATE,SEXE,AGE,CAS_IMPORTES,ID_GOV) values ('55877790','Bizerte',to_date('20/12/20','DD/MM/RR'),'F','20','0','11');
Insert into PROJET.PERSONNE (CIN,GOV,DATE_UPDATE,SEXE,AGE,CAS_IMPORTES,ID_GOV) values ('45364655','Sousse',to_date('01/01/20','DD/MM/RR'),'F','2','0','13');
Insert into PROJET.PERSONNE (CIN,GOV,DATE_UPDATE,SEXE,AGE,CAS_IMPORTES,ID_GOV) values ('46514655','Sousse',to_date('01/01/20','DD/MM/RR'),'F','44','0','13');
Insert into PROJET.PERSONNE (CIN,GOV,DATE_UPDATE,SEXE,AGE,CAS_IMPORTES,ID_GOV) values ('33333333','Sousse',to_date('01/01/20','DD/MM/RR'),'F','99','0','13');
Insert into PROJET.PERSONNE (CIN,GOV,DATE_UPDATE,SEXE,AGE,CAS_IMPORTES,ID_GOV) values ('11558425','Kasserine',to_date('18/03/20','DD/MM/RR'),'F','20','1','41');
Insert into PROJET.PERSONNE (CIN,GOV,DATE_UPDATE,SEXE,AGE,CAS_IMPORTES,ID_GOV) values ('98465984','Kasserine',to_date('18/03/20','DD/MM/RR'),'M','25','1','41');
REM INSERTING into PROJET.USERS
SET DEFINE OFF;
Insert into PROJET.USERS (ID,ADMIN,LOGIN,PASSWORD) values ('3','1','eya1','123');
Insert into PROJET.USERS (ID,ADMIN,LOGIN,PASSWORD) values ('4','1','siwar1','123');
Insert into PROJET.USERS (ID,ADMIN,LOGIN,PASSWORD) values ('1','0','eya','123');
Insert into PROJET.USERS (ID,ADMIN,LOGIN,PASSWORD) values ('2','0','siwar','123');
--------------------------------------------------------
--  DDL for Index DEMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."DEMANDE_PK" ON "PROJET"."DEMANDE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HOSPITALE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."HOSPITALE_PK" ON "PROJET"."HOPITALE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."USERS_PK" ON "PROJET"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GOUVERNORAT_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."GOUVERNORAT_PK1" ON "PROJET"."GOUVERNORAT" ("NOMGV", "ID_G", "DATE_UPDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GOUVERNORAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."GOUVERNORAT_PK" ON "PROJET"."PAYS" ("NOMPAYS", "ID_PAYS", "DATE_UPDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONNE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."PERSONNE_PK" ON "PROJET"."PERSONNE" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger DEMANDE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROJET"."DEMANDE_TRG" 
BEFORE INSERT ON DEMANDE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT DEMANDE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROJET"."DEMANDE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger GOUVERNORAT_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROJET"."GOUVERNORAT_SEQ" 
BEFORE INSERT ON GOUVERNORAT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NOMGV IS NULL THEN
      SELECT GOUVERNORAT_SEQ.NEXTVAL INTO :NEW.NOMGV FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROJET"."GOUVERNORAT_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HOPITALE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROJET"."HOPITALE_TRG" 
BEFORE INSERT ON HOPITALE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROJET"."HOPITALE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PAYS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROJET"."PAYS_TRG" 
BEFORE INSERT ON PAYS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROJET"."PAYS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROJET"."USERS_TRG" 
BEFORE INSERT ON USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT USERS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROJET"."USERS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table DEMANDE
--------------------------------------------------------

  ALTER TABLE "PROJET"."DEMANDE" ADD CONSTRAINT "DEMANDE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJET"."DEMANDE" MODIFY ("RESPONSABLE" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."DEMANDE" MODIFY ("DISTINATAIRE" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."DEMANDE" MODIFY ("TITRE" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."DEMANDE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."DEMANDE" MODIFY ("ID_HOSPITAL" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."DEMANDE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONNE
--------------------------------------------------------

  ALTER TABLE "PROJET"."PERSONNE" MODIFY ("ID_GOV" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."PERSONNE" MODIFY ("CAS_IMPORTES" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."PERSONNE" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."PERSONNE" MODIFY ("SEXE" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."PERSONNE" MODIFY ("DATE_UPDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."PERSONNE" MODIFY ("GOV" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."PERSONNE" ADD CONSTRAINT "PERSONNE_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJET"."PERSONNE" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYS
--------------------------------------------------------

  ALTER TABLE "PROJET"."PAYS" MODIFY ("NVL_CRITIQUE" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."PAYS" MODIFY ("CONTINENT" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."PAYS" MODIFY ("TOTAL_TEST" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."PAYS" MODIFY ("TOTAL_RECUPERE" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."PAYS" MODIFY ("TOTAL_DECES" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."PAYS" MODIFY ("TOTAL_CAS" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."PAYS" ADD CONSTRAINT "GOUVERNORAT_PK" PRIMARY KEY ("NOMPAYS", "ID_PAYS", "DATE_UPDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJET"."PAYS" MODIFY ("DATE_UPDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."PAYS" MODIFY ("ID_PAYS" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."PAYS" MODIFY ("NOMPAYS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOPITALE
--------------------------------------------------------

  ALTER TABLE "PROJET"."HOPITALE" ADD CONSTRAINT "HOSPITALE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJET"."HOPITALE" MODIFY ("GOV" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."HOPITALE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "PROJET"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJET"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."USERS" MODIFY ("ADMIN" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."USERS" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GOUVERNORAT
--------------------------------------------------------

  ALTER TABLE "PROJET"."GOUVERNORAT" ADD CONSTRAINT "GOUV_PK" PRIMARY KEY ("NOMGV", "ID_G", "DATE_UPDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJET"."GOUVERNORAT" MODIFY ("NVL_CRITIQUE" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."GOUVERNORAT" MODIFY ("NVL_TEST" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."GOUVERNORAT" MODIFY ("TOTAL_TEST" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."GOUVERNORAT" MODIFY ("NVL_RECUPERE" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."GOUVERNORAT" MODIFY ("TOTAL_RECUPERE" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."GOUVERNORAT" MODIFY ("NVL_DECES" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."GOUVERNORAT" MODIFY ("TOTAL_DECES" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."GOUVERNORAT" MODIFY ("NVL_CAS" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."GOUVERNORAT" MODIFY ("TOTAL_CAS" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."GOUVERNORAT" MODIFY ("DATE_UPDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."GOUVERNORAT" MODIFY ("ID_G" NOT NULL ENABLE);
  ALTER TABLE "PROJET"."GOUVERNORAT" MODIFY ("NOMGV" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DEMANDE
--------------------------------------------------------

  ALTER TABLE "PROJET"."DEMANDE" ADD CONSTRAINT "DEMANDE_FK1" FOREIGN KEY ("ID_HOSPITAL")
	  REFERENCES "PROJET"."HOPITALE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONNE
--------------------------------------------------------

  ALTER TABLE "PROJET"."PERSONNE" ADD CONSTRAINT "PERSONNE_FK1" FOREIGN KEY ("GOV", "ID_GOV", "DATE_UPDATE")
	  REFERENCES "PROJET"."GOUVERNORAT" ("NOMGV", "ID_G", "DATE_UPDATE") ON DELETE CASCADE ENABLE;
